INSERT INTO public.cities (name, active) VALUES
('Mérida', true),
('Navalmoral de la Mata', true),
('Salamanca', true),
('Badajoz', true),
('Cáceres', true),
('A Coruña', true),
('Sevilla', true),
('Zaragoza', true),
('Valencia', true),
('Plasencia', true),
('Talavera de la Reina', true),
('Málaga', true),
('Pamplona', true),
('Murcia', true),
('Palma de Mallorca', true),
('Las Palmas', true),
('Badalona', true),
('Granollers', true);
